### ISSUE TITLE
vesselinfo appears missing from installers

### ISSUE THREAD

**Issue by choksi81** [SeattleTestbed/dist#133]
Over the last five years, we have seen a handful of reports claiming that the ```vesselinfo``` file is missing from the installer tarball. Upon closer inspection, the file is actually there, but it has an extra ```./``` prefixed to its path which the other files in the tarball don't have. (Note that this is true for ''all'' of our installer tarballs, not specific to the troublesome ones!)

```
seattle/seattle_repy/deserialize.repy
seattle/seattle_repy/math.repy
seattle/seattle_repy/servicelookup.repy
# etc., etc.
./seattle/seattle_repy/
./seattle/seattle_repy/vesselinfo 
```

This prefix is probably the cause of the problem. The prefix comes into existence like this (see wiki:InstallerWorkflow for additional details): The [custom installer builder packager](source:seattle/trunk/custominstallerbuilder/common/packager.py#L127) takes the base installer ```tar``` file and appends the ```vesselinfo``` file to it. The directory (and thus file) appended to the archive is defined in [line 95](source:seattle/trunk/custominstallerbuilder/common/packager.py#L95) to be, variables expanded, ```./seattle/seattle_repy```.

Removing the trailing ```./``` from the directory string (see patch below) also removes it from the directory name as seen in the ```tar``` file:

```
seattle/seattle_repy/deserialize.repy
seattle/seattle_repy/math.repy
seattle/seattle_repy/servicelookup.repy
# etc.
seattle/seattle_repy/
seattle/seattle_repy/vesselinfo
```

----
I will ask the most recent reporter of this bug to try an installer tarball built using the new method and see if that fixes the problem.

**Comment by aaaaalbert** [comment]
This is a custominstallerbuilder issue, really. Closing here, opening SeattleTestbed/custominstallerbuilder#9 instead.
