### ISSUE TITLE
Improve Windows 7 detection during install

### ISSUE THREAD

**Issue by choksi81** [SeattleTestbed/dist#93]
`seattleinstaller.py`, lines 259 and following, claims to detect Windows 7 using

```
version = platform.release()
  if version == "Vista" or version == "post2008server":
    # ...
```

This doesn't always work. As far as I tested on my clean install of Windows 7 Professional (64 bit, German localization), version strings are:

|| '''Python version(s)''' || '''platform.release() string''' ||
|| 2.5.2 and 2.5.4 || Vista ||
|| 2.6.2 to 2.6.5 || post2008Server (note capitalization) ||
|| 2.6.6 and 2.7.0 to 2.7.3 || 7 ||

(See http://bugs.python.org/issue7863 for additional details.)

The lack of "7" and the wrong capitalization of "post2008Server" could be the reason that installing on Windows 7 sometimes fail. So, assuming that the startup behavior of Win7 didn't change over Windows Vista, line 260 of seattleinstaller.py needs to be changed to 

`if version == "Vista" or version == "post2008Server" or version == "7":`

Obviously, the comment block above the statement should be fixed as well. If we were pedantic, the variable `version` should be renamed `release` to avoid the perceived name clash with the function `platform.version()`.

Please drop me a line if I can go ahead with patching.

**Comment by aaaaalbert** [comment]
See also #146
