### ISSUE TITLE
make base installers needs refactoring...

### ISSUE THREAD

**Issue by choksi81** [SeattleTestbed/dist#97]
The code for make_base_installers is appallingly bad.   It really needs to be refactored.   Right now, there are huge parts of the code that are copy / pasted.

**Comment by aaaaalbert** [comment]
This issue triggered a cleaned-up Python port of the same script: https://github.com/SeattleTestbed/installer-packaging/blob/master/rebuild_base_installers.py

All further development is going to happen there. Closing!
